export const PROFILE_SET_NAME = 'PROFILE/PROFILE_SET_NAME';
export const PROFILE_LOAGING_TRUE = 'PROFILE/PROFILE_LOAGING_TRUE';
export const PROFILE_LOAGING_FALSE = 'PROFILE/PROFILE_LOAGING_FALSE';

export const PROFILE_GET = 'PROFILE/PROFILE_GET';
