export const USER_LOGIN = 'AUTH/USER_LOGIN';
export const USER_LOGOUT = 'AUTH/USER_LOGOUT';
export const USER_REGISTER = 'AUTH/USER_REGISTER';
export const FORM_SEND_TRUE = 'AUTH/FORM_SEND_TRUE';
export const FORM_SEND_FALSE = 'AUTH/FORM_SEND_FALSE';
