export const STORY_CREATE = 'STORY/STORY_CREATE';
export const STORY_FETCH = 'STORY/STORY_FETCH';
export const STORY_LOADING_TRUE = 'STORY/STORY_LOADING_TRUE';
export const STORY_LOADING_FALSE = 'STORY/STORY_LOADING_FALSE';
